export LANG="en_US.utf8"
export LC_ALL="en_US.utf8"

export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk-11.0.1.jdk/Contents/Home"
export PATH="/Users/tuanpham/libs/bin:/Users/tuanpham/libs/apache-maven-3.6.0/bin:$PATH"

export HOMEBREW_NO_AUTO_UPDATE=1


export PS1="\[\033[41m\]\[\033[1;33m\] ☭ \[\033[00m\]\[\033[01;32m\] \h:\W \u \$ \[\033[00m\]"
export EDITOR=nvim
export VISUAL="$EDITOR"

. ~/.bash_aliases
